#!/usr/bin/env fish

function logger-warn
  set_color magenta
  echo "$prefix [Warn] $argv[1..-1]"
  set_color normal
end
function logger-error
  set_color red
  echo "$prefix [Error] $argv[1..-1]"
  set_color normal
end
function logger-info
  set_color normal
  echo "$prefix [Info] $argv[1..-1]"
  set_color normal
end
function logger-debug
  set_color yellow
  echo "$prefix [Debug] $argv[1..-1]"
  set_color normal
end
function logger-success
  set_color green
  echo "$prefix [Succeeded] $argv[1..-1]"
  set_color normal
end
function logger -d "a lib to print msg quickly"
switch $argv[1]
case 0
  logger-info $argv[2..-1]
case 1
  logger-success $argv[2..-1]
case 2
  logger-debug $argv[2..-1]
case 3
  logger-warn $argv[2..-1]
case 4
  logger-error $argv[2..-1]
end
end

function help_echo
  echo "==========Help Documentation=========="
  set_color green
  echo "(./)app argv[1]"
  set_color normal
  echo " -argv[1]:the command to execute"
  echo "  -Available:
      debian_based >>> Build debian_based distro,use -a to build them all
      arch_based {archlinux,manjarolinux} >>> build archbased distro
      voidlinux >>> build voidlinux
      downloadable >>> build all downloadable image"
  echo "======================================"
end

function install
set installname $argv[1]
  set dir (pwd)
  set filename (status --current-filename)
  chmod +x $dir/$filename
  sudo cp $dir/$filename /usr/bin/$installname
  set_color green
  echo "$prefix Installed"
  set_color normal
end
function uninstall
set installname $argv[1]
  sudo rm /usr/bin/$installname
  set_color green
  echo "$prefix Removed"
  set_color normal
end

function centos
    logger 3 "Building centos7 amd64"
    if sudo distrobuilder build-lxc ./files/centos.yaml -o image.architecture=x86_64 -o image.release=7 -o image.variant=default -o source.url=http://mirrors.nju.edu.cn/centos/ -o source.skip_verification=true
        rm meta.tar.xz && mv rootfs.tar.xz centos7
    else
        logger 4 "error when building centos7 amd64"
    end
    logger 3 "Building centos7 arm64"
    if sudo distrobuilder build-lxc ./files/centos.yaml -o image.architecture=aarch64 -o image.release=7 -o image.variant=default -o source.url=http://mirrors.nju.edu.cn/centos-altarch/ -o source.skip_verification=true
        rm meta.tar.xz && mv rootfs.tar.xz centos7arm64
    else
        logger 4 "error when building centos7 arm64"
    end


    logger 3 "Building centos8 amd64"
    if sudo distrobuilder build-lxc ./files/centos.yaml -o image.architecture=x86_64 -o image.release=8-Stream -o image.variant=default -o source.url=http://mirrors.nju.edu.cn/centos/ -o source.skip_verification=true
        rm meta.tar.xz && mv rootfs.tar.xz centos8
    else
        logger 4 "error when building centos8 amd64"
    end
    logger 3 "Building centos8 arm64"
    if sudo distrobuilder build-lxc ./files/centos.yaml -o image.architecture=aarch64 -o image.release=8-Stream -o image.variant=default -o source.url=http://mirrors.nju.edu.cn/centos-altarch/ -o source.skip_verification=true
        rm meta.tar.xz && mv rootfs.tar.xz centos8arm64
    else
        logger 4 "error when building centos8 arm64"
    end
end
function alpinelinux
    logger 3 "Building alpinelinux edge amd64"
    if sudo distrobuilder build-lxc ./files/alpinelinux.yaml -o image.architecture=x86_64 -o image.release=edge -o image.variant=default
        rm meta.tar.xz && mv rootfs.tar.xz alpinelinux
    else
        logger 4 "error when building alpinelinux edge amd64"
    end
    logger 3 "Building alpinelinux edge arm64"
    if sudo distrobuilder build-lxc ./files/alpinelinux.yaml -o image.architecture=aarch64 -o image.release=edge -o image.variant=default
        rm meta.tar.xz && mv rootfs.tar.xz alpinelinuxarm64
    else
        logger 4 "error when building alpinelinux edge arm64"
    end
end

function archlinux
    logger 3 "Building archlinux amd64"
    if sudo distrobuilder build-lxc ./files/archlinux.yaml -o image.architecture=x86_64 -o image.variant=default
        rm meta.tar.xz && mv rootfs.tar.xz archlinux
    else
        logger 4 "error when building archlinux amd64"
    end
    logger 3 "Building archlinux arm64"
    if sudo distrobuilder build-lxc ./files/archlinux.yaml -o image.architecture=aarch64 -o image.variant=default
        rm meta.tar.xz && mv rootfs.tar.xz archlinuxarm64
    else
        logger 4 "error when building archlinux arm64"
    end
end

function debian
    logger 3 "Building debian-stable amd64"
    if sudo distrobuilder build-lxc ./files/debian.yaml -o image.architecture=amd64 -o image.release=bullseye -o image.variant=default -o source.url="http://mirrors.bfsu.edu.cn/debian"
        rm meta.tar.xz && mv rootfs.tar.xz debian-stable
    else
        logger 4 "error when building debian-stable amd64"
    end
    logger 3 "Building debian-stable arm64"
    if sudo distrobuilder build-lxc ./files/debian.yaml -o image.architecture=arm64 -o image.release=bullseye -o image.variant=default -o source.url="http://mirrors.bfsu.edu.cn/debian"
        rm meta.tar.xz && mv rootfs.tar.xz debian-stablearm64
    else
        logger 4 "error when building debian-stable arm64"
    end
end

function voidlinux
    cd /ctcontainer_share
    if test -d voidlinux
    else
        mkdir voidlinux
    end
    XBPS_ARCH=x86_64 HTTP_PROXY=http://127.0.0.1:7890/ xbps-install -S -r voidlinux -R "https://alpha.de.repo.voidlinux.org/current" base-minimal fish-shell bash ncurses
    cd voidlinux
    tar zcf voidlinux.tar.gz .
    cd ..
    mv voidlinux/voidlinux.tar.gz .
end

echo Build_Time_UTC=2022-05-28_03:52:29
set -lx prefix [ctc-rootfs-build-system]
switch $argv[1]
case debian
    debian
case archlinux
    archlinux
case centos
    centos
case alpinelinux
    alpinelinux
case voidlinux
    voidlinux
case v version
    logger 0 "Quicksand@build1"
case help h '*'
    help_echo
end